version: "4.14.1"
services: 
  db: 
    image: mysql
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  depends_on:
    - php
    - mysql