version: "4.14.1"
services:
  redis:
    image: "redis:3.2.3"
    hostname: redis

  redis-commander:
    build: https://github.com/djonatant/crud-project.git
    command: --redis-host redis
    links:
      - "redis:redis"
    ports:
      - 8081
  depends_on:
    - php
    - mysql